// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvhyikjftreggqrvnjyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aHlpa2pmdHJlZ2dxcnZuanl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDQ5ODEsImV4cCI6MjA3MDYyMDk4MX0.U693rPkMItiECTm1oPKGzr_KIPSCXPJa9GNf2h1y408";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});